name: flutter_tecnocholloapp
description: A simple Flutter project that showcases how to use the BLoC pattern for authentication.

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  http: ^0.13.5
  get_it: ^7.2.0
  injectable: ^2.1.0
  http_interceptor: ^1.0.1
  shared_preferences: ^2.0.17
  flutter_form_bloc: ^0.30.1
  flutter_svg : ^2.0.5
 

  flutter:
    sdk: flutter

 
 
  cupertino_icons: ^1.0.5
  bloc_concurrency: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3    



flutter:

 
 
 
  uses-material-design: true
